// Generated by gencpp from file littlecar/command.msg
// DO NOT EDIT!


#ifndef LITTLECAR_MESSAGE_COMMAND_H
#define LITTLECAR_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace littlecar
{
template <class ContainerAllocator>
struct command_
{
  typedef command_<ContainerAllocator> Type;

  command_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , th(0.0)  {
    }
  command_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::littlecar::command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::littlecar::command_<ContainerAllocator> const> ConstPtr;

}; // struct command_

typedef ::littlecar::command_<std::allocator<void> > command;

typedef boost::shared_ptr< ::littlecar::command > commandPtr;
typedef boost::shared_ptr< ::littlecar::command const> commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::littlecar::command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::littlecar::command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::littlecar::command_<ContainerAllocator1> & lhs, const ::littlecar::command_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::littlecar::command_<ContainerAllocator1> & lhs, const ::littlecar::command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace littlecar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::littlecar::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::littlecar::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::littlecar::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::littlecar::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::littlecar::command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::littlecar::command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::littlecar::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da9430b3caf9fc645e5c8737f6a2d6b5";
  }

  static const char* value(const ::littlecar::command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda9430b3caf9fc64ULL;
  static const uint64_t static_value2 = 0x5e5c8737f6a2d6b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::littlecar::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "littlecar/command";
  }

  static const char* value(const ::littlecar::command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::littlecar::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 th\n"
;
  }

  static const char* value(const ::littlecar::command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::littlecar::command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::littlecar::command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::littlecar::command_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "th: ";
    Printer<double>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LITTLECAR_MESSAGE_COMMAND_H
