// Generated by gencpp from file taskweek3/reply_acr_floatRequest.msg
// DO NOT EDIT!


#ifndef TASKWEEK3_MESSAGE_REPLY_ACR_FLOATREQUEST_H
#define TASKWEEK3_MESSAGE_REPLY_ACR_FLOATREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace taskweek3
{
template <class ContainerAllocator>
struct reply_acr_floatRequest_
{
  typedef reply_acr_floatRequest_<ContainerAllocator> Type;

  reply_acr_floatRequest_()
    : rand_gen(0.0)  {
    }
  reply_acr_floatRequest_(const ContainerAllocator& _alloc)
    : rand_gen(0.0)  {
  (void)_alloc;
    }



   typedef float _rand_gen_type;
  _rand_gen_type rand_gen;





  typedef boost::shared_ptr< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reply_acr_floatRequest_

typedef ::taskweek3::reply_acr_floatRequest_<std::allocator<void> > reply_acr_floatRequest;

typedef boost::shared_ptr< ::taskweek3::reply_acr_floatRequest > reply_acr_floatRequestPtr;
typedef boost::shared_ptr< ::taskweek3::reply_acr_floatRequest const> reply_acr_floatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator1> & lhs, const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rand_gen == rhs.rand_gen;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator1> & lhs, const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace taskweek3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88a85786e32d7174483f6783f29c251f";
  }

  static const char* value(const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88a85786e32d7174ULL;
  static const uint64_t static_value2 = 0x483f6783f29c251fULL;
};

template<class ContainerAllocator>
struct DataType< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "taskweek3/reply_acr_floatRequest";
  }

  static const char* value(const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 rand_gen\n"
;
  }

  static const char* value(const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rand_gen);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reply_acr_floatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taskweek3::reply_acr_floatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::taskweek3::reply_acr_floatRequest_<ContainerAllocator>& v)
  {
    s << indent << "rand_gen: ";
    Printer<float>::stream(s, indent + "  ", v.rand_gen);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASKWEEK3_MESSAGE_REPLY_ACR_FLOATREQUEST_H
