// Generated by gencpp from file taskweek3/reply_acr_float.msg
// DO NOT EDIT!


#ifndef TASKWEEK3_MESSAGE_REPLY_ACR_FLOAT_H
#define TASKWEEK3_MESSAGE_REPLY_ACR_FLOAT_H

#include <ros/service_traits.h>


#include <taskweek3/reply_acr_floatRequest.h>
#include <taskweek3/reply_acr_floatResponse.h>


namespace taskweek3
{

struct reply_acr_float
{

typedef reply_acr_floatRequest Request;
typedef reply_acr_floatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reply_acr_float
} // namespace taskweek3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::taskweek3::reply_acr_float > {
  static const char* value()
  {
    return "d030f27518f7e6a87b5fa3d9016849a2";
  }

  static const char* value(const ::taskweek3::reply_acr_float&) { return value(); }
};

template<>
struct DataType< ::taskweek3::reply_acr_float > {
  static const char* value()
  {
    return "taskweek3/reply_acr_float";
  }

  static const char* value(const ::taskweek3::reply_acr_float&) { return value(); }
};


// service_traits::MD5Sum< ::taskweek3::reply_acr_floatRequest> should match
// service_traits::MD5Sum< ::taskweek3::reply_acr_float >
template<>
struct MD5Sum< ::taskweek3::reply_acr_floatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::taskweek3::reply_acr_float >::value();
  }
  static const char* value(const ::taskweek3::reply_acr_floatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::taskweek3::reply_acr_floatRequest> should match
// service_traits::DataType< ::taskweek3::reply_acr_float >
template<>
struct DataType< ::taskweek3::reply_acr_floatRequest>
{
  static const char* value()
  {
    return DataType< ::taskweek3::reply_acr_float >::value();
  }
  static const char* value(const ::taskweek3::reply_acr_floatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::taskweek3::reply_acr_floatResponse> should match
// service_traits::MD5Sum< ::taskweek3::reply_acr_float >
template<>
struct MD5Sum< ::taskweek3::reply_acr_floatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::taskweek3::reply_acr_float >::value();
  }
  static const char* value(const ::taskweek3::reply_acr_floatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::taskweek3::reply_acr_floatResponse> should match
// service_traits::DataType< ::taskweek3::reply_acr_float >
template<>
struct DataType< ::taskweek3::reply_acr_floatResponse>
{
  static const char* value()
  {
    return DataType< ::taskweek3::reply_acr_float >::value();
  }
  static const char* value(const ::taskweek3::reply_acr_floatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASKWEEK3_MESSAGE_REPLY_ACR_FLOAT_H
