// Generated by gencpp from file taskweek3/reply_acr_floatResponse.msg
// DO NOT EDIT!


#ifndef TASKWEEK3_MESSAGE_REPLY_ACR_FLOATRESPONSE_H
#define TASKWEEK3_MESSAGE_REPLY_ACR_FLOATRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace taskweek3
{
template <class ContainerAllocator>
struct reply_acr_floatResponse_
{
  typedef reply_acr_floatResponse_<ContainerAllocator> Type;

  reply_acr_floatResponse_()
    : answer(0)  {
    }
  reply_acr_floatResponse_(const ContainerAllocator& _alloc)
    : answer(0)  {
  (void)_alloc;
    }



   typedef int8_t _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct reply_acr_floatResponse_

typedef ::taskweek3::reply_acr_floatResponse_<std::allocator<void> > reply_acr_floatResponse;

typedef boost::shared_ptr< ::taskweek3::reply_acr_floatResponse > reply_acr_floatResponsePtr;
typedef boost::shared_ptr< ::taskweek3::reply_acr_floatResponse const> reply_acr_floatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator1> & lhs, const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator1> & lhs, const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace taskweek3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3d074dd639894b3d0b9a5a1a5c4932a";
  }

  static const char* value(const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3d074dd639894b3ULL;
  static const uint64_t static_value2 = 0xd0b9a5a1a5c4932aULL;
};

template<class ContainerAllocator>
struct DataType< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "taskweek3/reply_acr_floatResponse";
  }

  static const char* value(const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 answer\n"
"\n"
;
  }

  static const char* value(const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reply_acr_floatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taskweek3::reply_acr_floatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::taskweek3::reply_acr_floatResponse_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<int8_t>::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASKWEEK3_MESSAGE_REPLY_ACR_FLOATRESPONSE_H
